language: go

env:
  - GO111MODULE=on

go:
  - 1.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - sudo apt-get install libzmq4-dev
  - go get -t -v ./...

script:
  - go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
